/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { LibTokenatxor, LibTokenatxorInterface } from "../LibTokenatxor";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "wisdom",
        type: "uint256",
      },
    ],
    name: "TokenatxorInteract",
    type: "event",
  },
];

const _bytecode =
  "0x602d6037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea164736f6c6343000802000a";

export class LibTokenatxor__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<LibTokenatxor> {
    return super.deploy(overrides || {}) as Promise<LibTokenatxor>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): LibTokenatxor {
    return super.attach(address) as LibTokenatxor;
  }
  connect(signer: Signer): LibTokenatxor__factory {
    return super.connect(signer) as LibTokenatxor__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LibTokenatxorInterface {
    return new utils.Interface(_abi) as LibTokenatxorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LibTokenatxor {
    return new Contract(address, _abi, signerOrProvider) as LibTokenatxor;
  }
}
