/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface ShopFacetInterface extends ethers.utils.Interface {
  functions: {
    "buyPortals(address,uint256)": FunctionFragment;
    "mintProductions(address,uint256)": FunctionFragment;
    "purchaseItemsWithTktr(address,uint256[],uint256[])": FunctionFragment;
    "purchaseTransferItemsWithTktr(address,uint256[],uint256[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "buyPortals",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintProductions",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseItemsWithTktr",
    values: [string, BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseTransferItemsWithTktr",
    values: [string, BigNumberish[], BigNumberish[]]
  ): string;

  decodeFunctionResult(functionFragment: "buyPortals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mintProductions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseItemsWithTktr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseTransferItemsWithTktr",
    data: BytesLike
  ): Result;

  events: {
    "BuyProductions(address,address,uint256,uint256,uint256)": EventFragment;
    "MintProductions(address,address,uint256,uint256,uint256)": EventFragment;
    "PurchaseItemsWithTktr(address,address,uint256[],uint256[],uint256)": EventFragment;
    "PurchaseItemsWithVouchers(address,address,uint256[],uint256[])": EventFragment;
    "PurchaseTransferItemsWithTktr(address,address,uint256[],uint256[],uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BuyProductions"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MintProductions"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PurchaseItemsWithTktr"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PurchaseItemsWithVouchers"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "PurchaseTransferItemsWithTktr"
  ): EventFragment;
}

export type BuyProductionsEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, BigNumber] & {
    _from: string;
    _to: string;
    _tokenId: BigNumber;
    _numProductionsToPurchase: BigNumber;
    _totalPrice: BigNumber;
  }
>;

export type MintProductionsEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, BigNumber] & {
    _from: string;
    _to: string;
    _tokenId: BigNumber;
    _numTokenatxorsToPurchase: BigNumber;
    _productionId: BigNumber;
  }
>;

export type PurchaseItemsWithTktrEvent = TypedEvent<
  [string, string, BigNumber[], BigNumber[], BigNumber] & {
    _buyer: string;
    _to: string;
    _itemIds: BigNumber[];
    _quantities: BigNumber[];
    _totalPrice: BigNumber;
  }
>;

export type PurchaseItemsWithVouchersEvent = TypedEvent<
  [string, string, BigNumber[], BigNumber[]] & {
    _buyer: string;
    _to: string;
    _itemIds: BigNumber[];
    _quantities: BigNumber[];
  }
>;

export type PurchaseTransferItemsWithTktrEvent = TypedEvent<
  [string, string, BigNumber[], BigNumber[], BigNumber] & {
    _buyer: string;
    _to: string;
    _itemIds: BigNumber[];
    _quantities: BigNumber[];
    _totalPrice: BigNumber;
  }
>;

export class ShopFacet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ShopFacetInterface;

  functions: {
    buyPortals(
      _to: string,
      _tktr: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    mintProductions(
      _to: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    purchaseItemsWithTktr(
      _to: string,
      _itemIds: BigNumberish[],
      _quantities: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    purchaseTransferItemsWithTktr(
      _to: string,
      _itemIds: BigNumberish[],
      _quantities: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  buyPortals(
    _to: string,
    _tktr: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  mintProductions(
    _to: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  purchaseItemsWithTktr(
    _to: string,
    _itemIds: BigNumberish[],
    _quantities: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  purchaseTransferItemsWithTktr(
    _to: string,
    _itemIds: BigNumberish[],
    _quantities: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    buyPortals(
      _to: string,
      _tktr: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    mintProductions(
      _to: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    purchaseItemsWithTktr(
      _to: string,
      _itemIds: BigNumberish[],
      _quantities: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    purchaseTransferItemsWithTktr(
      _to: string,
      _itemIds: BigNumberish[],
      _quantities: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "BuyProductions(address,address,uint256,uint256,uint256)"(
      _from?: string | null,
      _to?: string | null,
      _tokenId?: null,
      _numProductionsToPurchase?: null,
      _totalPrice?: null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber, BigNumber],
      {
        _from: string;
        _to: string;
        _tokenId: BigNumber;
        _numProductionsToPurchase: BigNumber;
        _totalPrice: BigNumber;
      }
    >;

    BuyProductions(
      _from?: string | null,
      _to?: string | null,
      _tokenId?: null,
      _numProductionsToPurchase?: null,
      _totalPrice?: null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber, BigNumber],
      {
        _from: string;
        _to: string;
        _tokenId: BigNumber;
        _numProductionsToPurchase: BigNumber;
        _totalPrice: BigNumber;
      }
    >;

    "MintProductions(address,address,uint256,uint256,uint256)"(
      _from?: string | null,
      _to?: string | null,
      _tokenId?: null,
      _numTokenatxorsToPurchase?: null,
      _productionId?: null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber, BigNumber],
      {
        _from: string;
        _to: string;
        _tokenId: BigNumber;
        _numTokenatxorsToPurchase: BigNumber;
        _productionId: BigNumber;
      }
    >;

    MintProductions(
      _from?: string | null,
      _to?: string | null,
      _tokenId?: null,
      _numTokenatxorsToPurchase?: null,
      _productionId?: null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber, BigNumber],
      {
        _from: string;
        _to: string;
        _tokenId: BigNumber;
        _numTokenatxorsToPurchase: BigNumber;
        _productionId: BigNumber;
      }
    >;

    "PurchaseItemsWithTktr(address,address,uint256[],uint256[],uint256)"(
      _buyer?: string | null,
      _to?: string | null,
      _itemIds?: null,
      _quantities?: null,
      _totalPrice?: null
    ): TypedEventFilter<
      [string, string, BigNumber[], BigNumber[], BigNumber],
      {
        _buyer: string;
        _to: string;
        _itemIds: BigNumber[];
        _quantities: BigNumber[];
        _totalPrice: BigNumber;
      }
    >;

    PurchaseItemsWithTktr(
      _buyer?: string | null,
      _to?: string | null,
      _itemIds?: null,
      _quantities?: null,
      _totalPrice?: null
    ): TypedEventFilter<
      [string, string, BigNumber[], BigNumber[], BigNumber],
      {
        _buyer: string;
        _to: string;
        _itemIds: BigNumber[];
        _quantities: BigNumber[];
        _totalPrice: BigNumber;
      }
    >;

    "PurchaseItemsWithVouchers(address,address,uint256[],uint256[])"(
      _buyer?: string | null,
      _to?: string | null,
      _itemIds?: null,
      _quantities?: null
    ): TypedEventFilter<
      [string, string, BigNumber[], BigNumber[]],
      {
        _buyer: string;
        _to: string;
        _itemIds: BigNumber[];
        _quantities: BigNumber[];
      }
    >;

    PurchaseItemsWithVouchers(
      _buyer?: string | null,
      _to?: string | null,
      _itemIds?: null,
      _quantities?: null
    ): TypedEventFilter<
      [string, string, BigNumber[], BigNumber[]],
      {
        _buyer: string;
        _to: string;
        _itemIds: BigNumber[];
        _quantities: BigNumber[];
      }
    >;

    "PurchaseTransferItemsWithTktr(address,address,uint256[],uint256[],uint256)"(
      _buyer?: string | null,
      _to?: string | null,
      _itemIds?: null,
      _quantities?: null,
      _totalPrice?: null
    ): TypedEventFilter<
      [string, string, BigNumber[], BigNumber[], BigNumber],
      {
        _buyer: string;
        _to: string;
        _itemIds: BigNumber[];
        _quantities: BigNumber[];
        _totalPrice: BigNumber;
      }
    >;

    PurchaseTransferItemsWithTktr(
      _buyer?: string | null,
      _to?: string | null,
      _itemIds?: null,
      _quantities?: null,
      _totalPrice?: null
    ): TypedEventFilter<
      [string, string, BigNumber[], BigNumber[], BigNumber],
      {
        _buyer: string;
        _to: string;
        _itemIds: BigNumber[];
        _quantities: BigNumber[];
        _totalPrice: BigNumber;
      }
    >;
  };

  estimateGas: {
    buyPortals(
      _to: string,
      _tktr: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    mintProductions(
      _to: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    purchaseItemsWithTktr(
      _to: string,
      _itemIds: BigNumberish[],
      _quantities: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    purchaseTransferItemsWithTktr(
      _to: string,
      _itemIds: BigNumberish[],
      _quantities: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    buyPortals(
      _to: string,
      _tktr: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    mintProductions(
      _to: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    purchaseItemsWithTktr(
      _to: string,
      _itemIds: BigNumberish[],
      _quantities: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    purchaseTransferItemsWithTktr(
      _to: string,
      _itemIds: BigNumberish[],
      _quantities: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
