/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface SvgViewsFacetInterface extends ethers.utils.Interface {
  functions: {
    "getItemSvgs(uint256)": FunctionFragment;
    "getItemsSvgs(uint256[])": FunctionFragment;
    "getTokenatxorSideSvgs(uint256)": FunctionFragment;
    "previewSideTokenatxor(uint256,address,int16[6],uint16[16])": FunctionFragment;
    "setSideViewDimensions(tuple[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getItemSvgs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getItemsSvgs",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenatxorSideSvgs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "previewSideTokenatxor",
    values: [
      BigNumberish,
      string,
      [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setSideViewDimensions",
    values: [
      {
        itemId: BigNumberish;
        side: string;
        dimensions: {
          x: BigNumberish;
          y: BigNumberish;
          width: BigNumberish;
          height: BigNumberish;
        };
      }[]
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "getItemSvgs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getItemsSvgs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenatxorSideSvgs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "previewSideTokenatxor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSideViewDimensions",
    data: BytesLike
  ): Result;

  events: {};
}

export class SvgViewsFacet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: SvgViewsFacetInterface;

  functions: {
    getItemSvgs(
      _itemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[]] & { svg_: string[] }>;

    getItemsSvgs(
      _itemIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<[string[][]] & { svgs_: string[][] }>;

    getTokenatxorSideSvgs(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[]] & { tr_: string[] }>;

    previewSideTokenatxor(
      _productionId: BigNumberish,
      _collateralType: string,
      _numericTraits: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      equippedEquippables: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      overrides?: CallOverrides
    ): Promise<[string[]] & { tr_: string[] }>;

    setSideViewDimensions(
      _sideViewDimensions: {
        itemId: BigNumberish;
        side: string;
        dimensions: {
          x: BigNumberish;
          y: BigNumberish;
          width: BigNumberish;
          height: BigNumberish;
        };
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getItemSvgs(
    _itemId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getItemsSvgs(
    _itemIds: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<string[][]>;

  getTokenatxorSideSvgs(
    _tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  previewSideTokenatxor(
    _productionId: BigNumberish,
    _collateralType: string,
    _numericTraits: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ],
    equippedEquippables: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ],
    overrides?: CallOverrides
  ): Promise<string[]>;

  setSideViewDimensions(
    _sideViewDimensions: {
      itemId: BigNumberish;
      side: string;
      dimensions: {
        x: BigNumberish;
        y: BigNumberish;
        width: BigNumberish;
        height: BigNumberish;
      };
    }[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getItemSvgs(
      _itemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getItemsSvgs(
      _itemIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<string[][]>;

    getTokenatxorSideSvgs(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    previewSideTokenatxor(
      _productionId: BigNumberish,
      _collateralType: string,
      _numericTraits: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      equippedEquippables: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      overrides?: CallOverrides
    ): Promise<string[]>;

    setSideViewDimensions(
      _sideViewDimensions: {
        itemId: BigNumberish;
        side: string;
        dimensions: {
          x: BigNumberish;
          y: BigNumberish;
          width: BigNumberish;
          height: BigNumberish;
        };
      }[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getItemSvgs(
      _itemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getItemsSvgs(
      _itemIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTokenatxorSideSvgs(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    previewSideTokenatxor(
      _productionId: BigNumberish,
      _collateralType: string,
      _numericTraits: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      equippedEquippables: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setSideViewDimensions(
      _sideViewDimensions: {
        itemId: BigNumberish;
        side: string;
        dimensions: {
          x: BigNumberish;
          y: BigNumberish;
          width: BigNumberish;
          height: BigNumberish;
        };
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getItemSvgs(
      _itemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getItemsSvgs(
      _itemIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTokenatxorSideSvgs(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    previewSideTokenatxor(
      _productionId: BigNumberish,
      _collateralType: string,
      _numericTraits: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      equippedEquippables: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setSideViewDimensions(
      _sideViewDimensions: {
        itemId: BigNumberish;
        side: string;
        dimensions: {
          x: BigNumberish;
          y: BigNumberish;
          width: BigNumberish;
          height: BigNumberish;
        };
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
